export const enum Icon {
	ARROW_UPWARD,
	ARROW_DOWNWARD,
	HEIGHT = "Height",
	KEYBOARD_ARROW_UP = "KeyboardArrowUp",
	KEYBOARD_ARROW_DOWN = "KeyboardArrowDown",
	KEYBOARD_DOUBLE_ARROW_UP = "KeyboardDoubleArrowUp",
	KEYBOARD_DOUBLE_ARROW_DOWN = "KeyboardDoubleArrowDown",
	KEYBOARD_ARROW_LEFT = "KeyboardArrowLeft",
	KEYBOARD_ARROW_RIGHT = "KeyboardArrowRight",
	KEYBOARD_DOUBLE_ARROW_LEFT = "KeyboardDoubleArrowLeft",
	KEYBOARD_DOUBLE_ARROW_RIGHT = "KeyboardDoubleArrowRight",
	KEYBOARD_BACKSPACE = "KeyboardBackspace",
	DELETE = "Delete",
	MORE_VERT = "MoreVert",
	SORT = "Sort",
	MOVE_UP = "MoveUp",
	MOVE_DOWN = "MoveDown",
	TEXT_SNIPPET = "TextSnippet",
	EDIT = "Edit",
	MORE_HORIZ = "MoreHoriz",
}
